// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInatallation() {
  return window['go']['deploy']['Deploy']['CancelInatallation']();
}

export function CheckNewVersion() {
  return window['go']['deploy']['Deploy']['CheckNewVersion']();
}

export function CheckSeedLabel() {
  return window['go']['deploy']['Deploy']['CheckSeedLabel']();
}

export function DeleteTempFiles() {
  return window['go']['deploy']['Deploy']['DeleteTempFiles']();
}

export function DoInstall() {
  return window['go']['deploy']['Deploy']['DoInstall']();
}

export function GetComputerInfo() {
  return window['go']['deploy']['Deploy']['GetComputerInfo']();
}

export function GetInstallPackages() {
  return window['go']['deploy']['Deploy']['GetInstallPackages']();
}

export function GetInstallStatus() {
  return window['go']['deploy']['Deploy']['GetInstallStatus']();
}

export function GetNetworkPinterList(arg1) {
  return window['go']['deploy']['Deploy']['GetNetworkPinterList'](arg1);
}

export function GetOAServer(arg1) {
  return window['go']['deploy']['Deploy']['GetOAServer'](arg1);
}

export function GetOS() {
  return window['go']['deploy']['Deploy']['GetOS']();
}

export function GetPrinterModels() {
  return window['go']['deploy']['Deploy']['GetPrinterModels']();
}

export function GetSeedLabel() {
  return window['go']['deploy']['Deploy']['GetSeedLabel']();
}

export function GetSelectedLocalPrinterDrivers(arg1) {
  return window['go']['deploy']['Deploy']['GetSelectedLocalPrinterDrivers'](arg1);
}

export function InitClient(arg1) {
  return window['go']['deploy']['Deploy']['InitClient'](arg1);
}

export function InstallAfterReboot() {
  return window['go']['deploy']['Deploy']['InstallAfterReboot']();
}

export function IsAdmin() {
  return window['go']['deploy']['Deploy']['IsAdmin']();
}

export function LoadTemporaryInfo() {
  return window['go']['deploy']['Deploy']['LoadTemporaryInfo']();
}

export function Reboot() {
  return window['go']['deploy']['Deploy']['Reboot']();
}

export function SetSelectedPrinters(arg1, arg2) {
  return window['go']['deploy']['Deploy']['SetSelectedPrinters'](arg1, arg2);
}
