// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function CancelInatallation():Promise<void>;

export function CheckNewVersion():Promise<boolean>;

export function CheckSeedLabel():Promise<boolean>;

export function DeleteTempFiles():Promise<void>;

export function DoInstall():Promise<void>;

export function GetComputerInfo():Promise<common.ComputerInfo>;

export function GetInstallPackages():Promise<Array<common.PackageInfo>>;

export function GetInstallStatus():Promise<Array<common.PackageInfo>>;

export function GetNetworkPinterList(arg1:string):Promise<Array<common.Printer>>;

export function GetOAServer(arg1:string):Promise<string>;

export function GetOS():Promise<string>;

export function GetPrinterModels():Promise<Array<common.PrinterModel>>;

export function GetSeedLabel():Promise<common.SeedInfo>;

export function GetSelectedLocalPrinterDrivers(arg1:string):Promise<Array<common.PackageInfo>>;

export function InitClient(arg1:string):Promise<void>;

export function InstallAfterReboot():Promise<void>;

export function IsAdmin():Promise<boolean>;

export function LoadTemporaryInfo():Promise<void>;

export function Reboot():Promise<void>;

export function SetSelectedPrinters(arg1:string,arg2:Array<common.Printer>):Promise<boolean>;
