// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartPage():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LogFromFrontend(arg1:string):Promise<void>;

export function ForceQuit():Promise<void>;
