// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetAllPackages():Promise<service.PackageInfo>;

export function GetComputerInfo():Promise<service.ComputerInfo>;

export function Greet(arg1:string):Promise<string>;
