// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPackages() {
  return window['go']['main']['App']['GetAllPackages']();
}

export function GetComputerInfo() {
  return window['go']['main']['App']['GetComputerInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
