// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetStartPage() {
  return window['go']['main']['App']['GetStartPage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogFromFrontend(arg1) {
  return window['go']['main']['App']['LogFromFrontend'](arg1);
}
